backend:
  name: git-gateway
  branch: master
media_folder: static/images/uploads
publish_mode: editorial_workflow
public_folder: src/images/uploads
site_url: https://russianhouse.netlify.app
display_url: https://russianhouse.netlify.app
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }